version: '3'
services:
  hora-certa:
    build:
      context: .
      args:
        - ENV=$ENV
      dockerfile: Dockerfile
    container_name: hora-certa
    image: hora-certa
    ports:
      - "8080:8080"
#    networks:
#      - default
#
#networks:
#  default:
#    external:
#      name: bluenetwork