version: '3'

services:
  hora-certa-repository:
    image: postgres
    restart: always
    container_name: hora-certa-repository
    environment:
      POSTGRES_USER: horacertamaster
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: horacertarepository
    ports:
      - "5432:5432"
    volumes:
      - ./db/init_data.sql:/docker-entrypoint-initdb.d/init_data.sql

  hora-certa:
    build:
      context: .
      args:
        - ENV=$ENV
      dockerfile: Dockerfile
    container_name: hora-certa
    ports:
      - "8080:8080"
